### ISSUE TITLE
You may use push instead.

### ISSUE THREAD

**Issue by AlexYalovoy** [Vladislav-Shvorobuk/JavaScript#22]
https://github.com/Vladislav-Shvorobuk/JavaScript/blob/3a90b0286c8e26a88adf7cad492ccda08b191e2b/src/index.js#L69

**Comment by Vladyslav-Shvorobuk** [comment]
If I use the push() method, I add one more task to the stack (If I am not wrong).
In addition, push() uses cycle "for". That is why this option works more longer.
If you don't mind, I will not change my code.
